version: "3"
x-common:
  networks:
    - signoz-net
  logging:
    options:
      max-size: 50m
      max-file: "3"
x-clickhouse-defaults:
  networks:
    - signoz-net
  logging:
    options:
      max-size: 50m
      max-file: "3"
  image: clickhouse/clickhouse-server:25.5.6
  tty: true
  labels:
    signoz.io/scrape: "true"
    signoz.io/port: "9363"
    signoz.io/path: /metrics
  depends_on:
    init-clickhouse:
      condition: service_completed_successfully
    zookeeper-1:
      condition: service_healthy
  healthcheck:
    test:
      - CMD
      - wget
      - --spider
      - -q
      - 0.0.0.0:8123/ping
    interval: 30s
    timeout: 5s
    retries: 3
  environment:
    - CLICKHOUSE_SKIP_USER_SETUP=1
x-zookeeper-defaults:
  networks:
    - signoz-net
  logging:
    options:
      max-size: 50m
      max-file: "3"
  image: signoz/zookeeper:3.7.1
  user: root
  labels:
    signoz.io/scrape: "true"
    signoz.io/port: "9141"
    signoz.io/path: /metrics
  healthcheck:
    test:
      - CMD-SHELL
      - curl -s -m 2 http://localhost:8080/commands/ruok | grep error | grep null
    interval: 30s
    timeout: 5s
    retries: 3
x-db-depend:
  networks:
    - signoz-net
  logging:
    options:
      max-size: 50m
      max-file: "3"
  depends_on:
    clickhouse:
      condition: service_healthy
    schema-migrator-sync:
      condition: service_completed_successfully
services:
  init-clickhouse:
    networks:
      - signoz-net
    restart: on-failure
    logging:
      options:
        max-size: 50m
        max-file: "3"
    image: clickhouse/clickhouse-server:25.5.6
    container_name: signoz-init-clickhouse
    command:
      - bash
      - -c
      - 'version="v0.0.1"

        node_os=$$(uname -s | tr ''[:upper:]'' ''[:lower:]'')

        node_arch=$$(uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)

        echo "Fetching histogram-binary for $${node_os}/$${node_arch}"

        cd /tmp

        wget -O histogram-quantile.tar.gz "https://github.com/SigNoz/signoz/releases/download/histogram-quantile%2F$${version}/histogram-quantile_$${node_os}_$${node_arch}.tar.gz"

        tar -xvzf histogram-quantile.tar.gz

        mv histogram-quantile /var/lib/clickhouse/user_scripts/histogramQuantile

        '
    volumes:
      - type: bind
        source: ./deploy/common/clickhouse/user_scripts
        target: /var/lib/clickhouse/user_scripts/
  zookeeper-1:
    networks:
      - signoz-net
    logging:
      options:
        max-size: 50m
        max-file: "3"
    image: signoz/zookeeper:3.7.1
    user: root
    labels:
      signoz.io/scrape: "true"
      signoz.io/port: "9141"
      signoz.io/path: /metrics
    healthcheck:
      test:
        - CMD-SHELL
        - curl -s -m 2 http://localhost:8080/commands/ruok | grep error | grep null
      interval: 30s
      timeout: 5s
      retries: 3
    container_name: signoz-zookeeper-1
    volumes:
      - type: volume
        source: zookeeper-1
        target: /bitnami/zookeeper
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ZOO_PROMETHEUS_METRICS_PORT_NUMBER=9141
  clickhouse:
    networks:
      - signoz-net
    logging:
      options:
        max-size: 50m
        max-file: "3"
    image: clickhouse/clickhouse-server:25.5.6
    tty: true
    labels:
      signoz.io/scrape: "true"
      signoz.io/port: "9363"
      signoz.io/path: /metrics
    depends_on:
      init-clickhouse:
        condition: service_completed_successfully
      zookeeper-1:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - 0.0.0.0:8123/ping
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    container_name: signoz-clickhouse
    volumes:
      - type: bind
        source: ./deploy/common/clickhouse/config.xml
        target: /etc/clickhouse-server/config.xml
        isDirectory: false
      - type: bind
        source: ./deploy/common/clickhouse/users.xml
        target: /etc/clickhouse-server/users.xml
        isDirectory: false
      - type: bind
        source: ./deploy/common/clickhouse/custom-function.xml
        target: /etc/clickhouse-server/custom-function.xml
        isDirectory: false
      - type: bind
        source: ./deploy/common/clickhouse/user_scripts
        target: /var/lib/clickhouse/user_scripts/
      - type: bind
        source: ./deploy/common/clickhouse/cluster.xml
        target: /etc/clickhouse-server/config.d/cluster.xml
        isDirectory: false
      - type: volume
        source: clickhouse
        target: /var/lib/clickhouse/
  signoz:
    networks:
      - signoz-net
    logging:
      options:
        max-size: 50m
        max-file: "3"
    depends_on:
      clickhouse:
        condition: service_healthy
      schema-migrator-sync:
        condition: service_completed_successfully
    image: signoz/signoz:${VERSION:-v0.94.1}
    container_name: signoz
    command:
      - --config=/root/config/prometheus.yml
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./deploy/common/signoz/prometheus.yml
        target: /root/config/prometheus.yml
        isDirectory: false
      - type: bind
        source: ./deploy/common/dashboards
        target: /root/config/dashboards
      - type: volume
        source: sqlite
        target: /var/lib/signoz/
    environment:
      - SIGNOZ_ALERTMANAGER_PROVIDER=signoz
      - SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN=tcp://clickhouse:9000
      - SIGNOZ_SQLSTORE_SQLITE_PATH=/var/lib/signoz/signoz.db
      - DASHBOARDS_PATH=/root/config/dashboards
      - STORAGE=clickhouse
      - GODEBUG=netdns=go
      - TELEMETRY_ENABLED=true
      - DEPLOYMENT_TYPE=docker-standalone-amd
      - DOT_METRICS_ENABLED=true
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - localhost:8080/api/v1/health
      interval: 30s
      timeout: 5s
      retries: 3
  otel-collector:
    networks:
      - signoz-net
    logging:
      options:
        max-size: 50m
        max-file: "3"
    depends_on:
      signoz:
        condition: service_healthy
    image: signoz/signoz-otel-collector:${OTELCOL_TAG:-v0.129.4}
    container_name: signoz-otel-collector
    command:
      - --config=/etc/otel-collector-config.yaml
      - --manager-config=/etc/manager-config.yaml
      - --copy-path=/var/tmp/collector-config.yaml
      - --feature-gates=-pkg.translator.prometheus.NormalizeName
    volumes:
      - type: bind
        source: ./deploy/docker/otel-collector-config.yaml
        target: /etc/otel-collector-config.yaml
        isDirectory: false
      - type: bind
        source: ./deploy/common/signoz/otel-collector-opamp-config.yaml
        target: /etc/manager-config.yaml
        isDirectory: false
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
      - LOW_CARDINAL_EXCEPTION_GROUPING=false
    ports:
      - 4317:4317
      - 4318:4318
  schema-migrator-sync:
    networks:
      - signoz-net
    restart: on-failure
    logging:
      options:
        max-size: 50m
        max-file: "3"
    image: signoz/signoz-schema-migrator:${OTELCOL_TAG:-v0.129.4}
    container_name: schema-migrator-sync
    command:
      - sync
      - --dsn=tcp://clickhouse:9000
      - --up=
    depends_on:
      clickhouse:
        condition: service_healthy
  schema-migrator-async:
    networks:
      - signoz-net
    restart: on-failure
    logging:
      options:
        max-size: 50m
        max-file: "3"
    depends_on:
      clickhouse:
        condition: service_healthy
      schema-migrator-sync:
        condition: service_completed_successfully
    image: signoz/signoz-schema-migrator:${OTELCOL_TAG:-v0.129.4}
    container_name: schema-migrator-async
    command:
      - async
      - --dsn=tcp://clickhouse:9000
      - --up=
networks:
  signoz-net:
    name: signoz-net
volumes:
  clickhouse:
    name: signoz-clickhouse
  sqlite:
    name: signoz-sqlite
  zookeeper-1:
    name: signoz-zookeeper-1
